### PR TITLE
Add a feature for listing all books borrowed by a given user by the administrator

### PR DESCRIPTION
**Pull request by meshack-mbuvi**
Add a feature for listing all books borrowed by a given user by the administrator.The following is the screenshot of the feature
prince

### CODE REVIEW

**Comment by Xerrex** [comment]
Very thoughtful..

**Comment by Nerldy** [comment]
Not bad. I would say that you try out a color scheme with better contrast. For example, the word price is getting lost because the blue and green are a little close in the value range.

**Comment by chebetsandra** [comment]
awesome job!

**Comment by meshack-mbuvi** [comment]
@Nerldy The issue of color has been taken care of as of now.

**Comment by meshack-mbuvi** [comment]
profile

**Pull request merged**
